
#################################################################
## Home Assistant

homeassistant:
  name: Home
  latitude: REDACTED
  longitude: REDACTED
  elevation: 250
  unit_system: imperial
  time_zone: America/Detroit
  packages: !include_dir_named packages/

group: !include groups.yaml

frontend:
  javascript_version: es5
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-tiles.html
  themes:
    dark:
      primary-color: '#36454f'

config:

http:
  server_port: REDACTED
  api_password: REDACTED
  base_url: REDACTED
  trusted_networks:
    - REDACTED
    - REDACTED
  ip_ban_enabled: true
  login_attempts_threshold: 5

updater:
  reporting: False

discovery:
  ignore:
    - plex_mediaserver

recorder:
  purge_interval: 1
  purge_keep_days: 5
  include:
    domains:
      - alarm_control_panel
      - device_tracker
      - binary_sensor
      - input_boolean
      - input_select
      - light
      - media_player
      - switch
    entities:
      - sensor.backdoor_contact
      - sensor.delivered_today
      - sensor.dishwasher_status
      - sensor.fedex
      - sensor.frontdoor_contact
      - sensor.meter_switch_current
      - sensor.meter_switch_power
      - sensor.out_for_delivery
      - sensor.packages_in_transit
      - sensor.sidedoor_contact
      - sensor.ups

  exclude:
    entities:
      - device_tracker.ipad
      - binary_sensor.backdoor_contact_sensor
      - binary_sensor.frontdoor_contact_sensor
      - binary_sensor.sidedoor_contact_sensor
      - light.hue_lamp_1
      - light.hue_lamp_2
      - light.hue_lamp_3
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3
      - light.hpmusicgroup
      - switch.nad_ccinput
      - switch.nad_power
      - switch.nad_volume

history:

logbook:

customizer:
  hide_attributes:
    - node_id
    - value_index
    - value_instance
    - value_id
    - old_entity_id
    - new_entity_id
    - google_assistant
    - google_assistant_name

ios:

twilio:
  account_sid: REDACTED
  auth_token: REDACTED

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: REDACTED
  - name: twilio_call
    platform: twilio_call
    from_number: REDACTED

google_assistant:
  expose_by_default: false
  project_id: REDACTED
  client_id: REDACTED
  access_token: REDACTED
  api_key: REDACTED
  agent_user_id: REDACTED

ifttt:
  key: REDACTED
