
#################################################################
## Home Assistant

homeassistant:
  name: Home Assistant
  latitude: !secret halatitude
  longitude: !secret halongitude
  elevation: 250
  unit_system: imperial
  time_zone: America/Detroit
  packages: !include_dir_named packages/

frontend:
  themes:
    dark:
      primary-color: '#36454f'

config:

http:
  server_port: !secret server_port
  api_password: !secret api_password
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5

group:
  default_view:
    view: yes

discovery:
  ignore:
    - plex_mediaserver

recorder:
  purge_interval: 1
  purge_keep_days: 3
  include:
    domains:
      - alarm_control_panel
      - binary_sensor
      - input_boolean
      - input_select
      - light
      - media_player
      - switch
      - vacuum
      - lock
      - automation
    entities:
      - sensor.dishwasher_status
      - sensor.meter_outlet_current
      - sensor.meter_outlet_power
      - sensor.kwikset_touchpad_electronic_deadbolt_alarm_level_2
      - sensor.kwikset_touchpad_electronic_deadbolt_alarm_type_2
      - sensor.dining_room_thermostat_temperature
      - sensor.dining_room_thermostat_humidity
      - sensor.home_assistant_release
      - sensor.current_version
  exclude:
    entities:
      - binary_sensor.backdoor_contact_sensor
      - binary_sensor.frontdoor_contact_sensor
      - binary_sensor.sidedoor_contact_sensor
      - binary_sensor.mckinley_away
      - binary_sensor.dining_room_thermostat_is_using_emergency_heat
      - binary_sensor.dining_room_thermostat_online
      - binary_sensor.dining_room_thermostat_is_locked
      - binary_sensor.dining_room_thermostat_has_leaf
      - binary_sensor.dining_room_thermostat_fan
      - light.hue_lamp_1
      - light.hue_lamp_2
      - light.hue_lamp_3
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3
      - light.hpmusicgroup
      - switch.nad_ccinput
      - switch.nad_power
      - switch.nad_volume
      - input_boolean.alarmclock_cancel
      - media_player.muffin_stuffin
      - input_boolean.manual_armed_away
      - input_boolean.manual_armed_home
      - input_select.playlist_content
      - input_select.playlist_source
      - switch.livingroom_outlet_switch_3
      - switch.livingroom_outlet_switch_2
      - switch.livingroom_outlet_switch

history:

logbook:

sun:

ios:

#################################################################
## Media Players

media_player:
  - platform: vizio
    name: viziotv
    host: !secret viziohost
    access_token: !secret vizioaccess_token
  - platform: nadtcp2
    name: nadc338
    max_volume: -20
    min_volume: -70
    host: !secret nadtcp2host


#################################################################
## Lights

zwave:
  usb_path: "/dev/ttyACM0"
  network_key: !secret network_key
  polling_interval: 30000
  device_config:
    light.livingroom_light_level:
      polling_intensity: 1
      refresh_value: true
    light.kitchen_light_level:
      polling_intensity: 1
      refresh_value: true
    light.diningroom_light_level:
      polling_intensity: 1
      refresh_value: true
    light.bedroom_light_level:
      polling_intensity: 1
      refresh_value: true
    light.bathroom_light_level:
      polling_intensity: 1
      refresh_value: true
    light.hallway_light_level:
      polling_intensity: 1
      refresh_value: true

light:
  - platform: hue
    host: !secret huehost
    allow_unreachable: true
    allow_hue_groups: true


#################################################################
## Things

nest:
  client_id: !secret nestclient_id
  client_secret: !secret nestclient_secret

vacuum:
  - platform: roomba
    host: !secret roombahost
    username: !secret roombausername
    password: !secret roombapassword

google_keep:
  username: !secret keepusername
  password: !secret keeppassword
  list_name: "Rob To Do"

weather:
  - platform: yweather

#################################################################
## Security / Occupancy

alarm_control_panel:
  platform: manual
  name: Main
  pending_time: 15
  trigger_time: 99999999

zoneminder:
  host: !secret zmhost
  path: /
  path_zms: /cgi-bin/nph-zms
  ssl: true
  username: homeassistant
  password: !secret zmpassword

camera:
  - platform: zoneminder
  - platform: generic
    still_image_url: https://icons.wxug.com/data/weather-maps/radar/united-states/cadillac-michigan-region-current-radar-animation.gif
    name: Midwest Radar

device_tracker:
  - platform: netgear
    host: !secret netgearhost
    username: !secret netgearusername
    password: !secret netgearpassword
    port: 80
    interval_seconds: 12
    new_device_defaults:
      track_new_devices: False

mqtt:
  broker: 127.0.0.1
  username: homeassistant
  password: !secret mqttpassword

zone:
  name: Home
  latitude: !secret zonelatitude
  longitude: !secret zonelongitude
  radius: 200


#################################################################
## Notifications and Google Assistant

twilio:
  account_sid: !secret twilioaccountsid
  auth_token: !secret twilioauthtoken

notify:
  - name: twilio_calling
    platform: twilio_call
    from_number: !secret twiliofromnumber
  - name: html5
    platform: html5
    gcm_api_key: !secret gcpapikey
    gcm_sender_id: !secret gcpsenderid
  - name: GA Broadcast
    platform: rest
    resource: http://127.0.0.1:5000/broadcast_message
  - name: GA Command
    platform: rest
    resource: http://127.0.0.1:5000/command


cloud:
  google_actions:
    filter:
      include_entities:
        - light.livingroom_light_level
        - light.kitchen_light_level
        - light.diningroom_light_level
        - light.bedroom_light_level
        - light.bathroom_light_level
        - light.hallway_light_level
        - light.nightstand
        - light.nightstand1
        - light.nightstand2
        - switch.bedroom_outlet_switch_3
        - switch.kitchen_outlet_switch
        - media_player.nadc338
        - media_player.viziotv
        - scene.dinner
        - scene.watching_tv
        - scene.goodmorning
        - scene.bedtime
        - scene.mia_bedtime
        - scene.all_things_off
        - script.roomba_on
        - script.cancel_alarm
        - script.playlist_stop
    entity_config:
      light.livingroom_light_level:
        name: Living Room Lights
      light.kitchen_light_level:
        name: Kitchen Lights
      light.diningroom_light_level:
        name: Dining Room Lights
      light.bedroom_light_level:
        name: Bedroom Lights
      light.bathroom_light_level:
        name: Bathroom Lights
      light.hallway_light_level:
        name: Hallway Lights
      light.nightstand:
        name: Nightstand Lights
      light.nightstand1:
        name: !secret user2ns
      light.nightstand2:
        name: !secret user1ns
      switch.bedroom_outlet_switch_3:
        name: Bedroom Fan Switch
        aliases:
          - Bedroom Fan
          - Fan
      switch.kitchen_outlet_switch:
        name: Espresso Machine Switch
        aliases:
          - Espresso Machine
          - Coffee Machine
          - Kitchen Outlet
      media_player.nadc338:
        name: Stereo Switch
        aliases:
          - Stereo
          - Nad
      media_player.viziotv:
        name: TV Switch
        aliases:
          - TV
          - Vizio
      scene.dinner:
        name: Dinner Scene
      scene.watching_tv:
        name: Watching TV Scene
      scene.goodmorning:
        name: GoodMorning Scene
      scene.bedtime:
        name: Bedtime Scene
      scene.mia_bedtime:
        name: Mia Bedtime
      scene.all_things_off:
        name: All Things Off Scene
      script.roomba_on:
        name: Roomba
      script.cancel_alarm:
        name: Cancel Alarm
      script.playlist_stop:
        name: Playlist Stop
