
#################################################################
## Components

#nest:
#  client_id: REDACTED
#  client_secret: REDACTED

vacuum:
  - platform: roomba
    host: REDACTED.247
    username: REDACTED
    password: 'REDACTED'

#################################################################
## Groups
group:

  devices:
    name: Things
    control: hidden
    entities:
      - vacuum.roomba
      - sensor.dishwasher_status
      - switch.kitchen_outlet_switch
      - switch.bedroom_outlet_switch_3


#################################################################
## Customize
homeassistant:
  customize:

    sensor.dishwasher_status:
      friendly_name: Dishwasher
      icon: mdi:washing-machine

    switch.meter_switch_switch:
      friendly_name: Dishwasher Switch

    sensor.meter_switch_current:
      friendly_name: Dishwasher Current

    sensor.meter_switch_power:
      friendly_name: Dishwasher Power

    switch.bedroom_outlet_switch_3:
      friendly_name: Bedroom Fan
      icon: mdi:fan

    switch.kitchen_outlet_switch:
      friendly_name: Espresso Machine
      icon: mdi:coffee

    switch.bedroom_outlet_switch_2:
      friendly_name: Bedroom Outlet Left

#    climate.dining_room:
#      friendly_name: Nest


#################################################################
## Sensors
sensor:

  - platform: template
    sensors:
      dishwasher_status:
        value_template: '{{ states.input_select.dishwasher_status.state}}'
        friendly_name: 'Dishwasher Status'


##################################################
## Inputs
input_select:

  dishwasher_status:
    name: Dishwasher Status
    options:
      - Running
      - Drying
      - 'Off'
    initial: 'Off'


#################################################################
## Automations
automation:

  # Espresso Notify
  - alias: Espresso Notify

    trigger:
      platform: state
      entity_id: switch.kitchen_outlet_switch
      to: 'on'
      for:
        minutes: 30

    action:
      service: notify.pushbullet
      data:
        message: 'Espresso machine is warmed up!'

  # Sceduled Roobma!!
  - alias: Roomba On Weekdays

    trigger:
      - platform: time
        at: '10:00:00'

    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: template
          value_template: '{{states.vacuum.roomba.attributes.battery_level > 80}}'

    action:
      - service: homeassistant.turn_on
        entity_id: vacuum.roomba

  # Notify when Roomba is finished
  - alias: Roomba notify finished

    trigger:
      - platform: state
        entity_id: vacuum.roomba
        from: 'on'
        to: 'off'

    condition:
      - condition: state
        entity_id: vacuum.roomba
        state: 'on'
        for:
          minutes: 50

    action:
      service: notify.pushbullet
      data:
        message: 'Schmidt is finished and bin is full.'
        title: 'Roomba Finished'

  # Notify when Roomba is error
#  - alias: Roomba notify error
#
#    trigger:
#      platform: state
#      entity_id: vacuum.roomba
#      from: 'on'
#      to: 'off'
#
#    condition:
#      - condition: template
#        value_template: '{{states.vacuum.roomba.attributes.battery_level > 80}}'
#
#    action:
#      service: notify.pushbullet
#      data:
#        message: 'Schmidt is stuck or something else is wrong.'
#        title: 'Roomba Error'


#Dishwasher logic
  # Dishwasher set running
  - alias: Set dishwasher active when power detected

    trigger:
      - platform: numeric_state
        entity_id: sensor.meter_switch_power
        above: 10

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: 'Off'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Running
   
  # Dishwasher set drying
  - alias: Set dishwasher drying when power drops

    trigger:
      - platform: numeric_state
        entity_id: sensor.meter_switch_power
        below: 600
        above: 380
        for:
          minutes: 2

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Running

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Drying
   
  # Dishwasher set off
  - alias: Set dishwasher off

    trigger:
      - platform: numeric_state
        entity_id: sensor.meter_switch_power
        below: 5
        for:
          minutes: 6

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: 'Off'

  # Dishwasher Alert when done
  - alias: Send alert when dishwasher is done

    trigger:
      - platform: state
        entity_id: input_select.dishwasher_status
        to: 'Off'

    action:
      service: notify.pushbullet
      data:
        message: 'The Dishwasher has finished and is ready to be emptied.'
        title: 'Dishwasher Finished'
