
#################################################################
## Groups
group:

  overridechild:
    name: Override
    control: hidden
    entities:
      - automation.motion_bathroom_lights_on_20min
      - automation.motion_hallway_lights_on_15min
      - automation.dark_arrive_home_lights
      - automation.turn_on_kitchen_lights_at_entry
      - automation.roomba_on_weekdays
      - group.alarmclock
      - switch.bedroom_outlet_switch_2
      - switch.meter_outlet_switch

  systemmgmt:
    name: System Management
    control: hidden
    entities:
      - input_boolean.vacation_mode
      - script.updateha
      - script.restartha
      - script.rebootpi


##################################################
## Inputs
input_boolean:

  vacation_mode:
    name: Vacation Mode
    initial: off
    icon: mdi:airplane-takeoff


##################################################
## Commands
shell_command:
  updateha: /home/homeassistant/.homeassistant/updateha.sh
  restartha: sudo systemctl restart home-assistant.service
  rebootpi: sudo reboot


##################################################
## Scripts
script:

  # Update HA
  updateha:
    alias: Update Home Assistant
    sequence:
      - service: shell_command.updateha

  # Restart Home Assistant
  restartha:
    alias: Restart Home Assistant
    sequence:
      - service: shell_command.restartha

  # Reboot Raspberry Pi
  rebootpi:
    alias: Reboot Raspberry Pi
    sequence:
      - service: shell_command.rebootpi

  # Notify package delivered
  package_notify:
    sequence:
      - service: notify.html5
        data:
          title: 'Package Delivered'
          message: 'A package has been delivered.'
          data:
            requireInteraction: true
            renotify: true
            tag: 'package_notify'


#################################################################
## Automations
automation:

  # Notify when HA update is availavle
  - alias: 'Update Available Notifications'

    trigger:
      platform: state
      entity_id: updater.updater

    action:
      - service: notify.html5
        data:
          title: 'New Home Assistant Release'
          message: 'Home Assistant  {{ states.updater.updater.state }}  is now available.'
          data:
            requireInteraction: true

  # Set HA theme on startup
  - alias: 'Set theme at startup'
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data:
        name: dark
