
#################################################
## Customize

homeassistant:
  customize:
    script.playlist_remote:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        row_height: 40px
        column_width: 60px
        gap: 10px
        entities:
          - entity: script.playlist_action
            icon: mdi:play
            color: '#9a9fa8'
            column: 1
            row: 1
          - entity: script.playlist_stop
            icon: mdi:stop
            color: '#9a9fa8'
            column: 2
            row: 1
          - entity: script.playlist_voldown
            icon: mdi:volume-medium
            color: '#9a9fa8'
            column: 3
            row: 1
          - entity: script.playlist_volup
            icon: mdi:volume-high
            color: '#9a9fa8'
            column: 4
            row: 1


#################################################################
## Groups
group:

  playlist_control:
    name: Playlist Control
    control: hidden
    entities:
    - input_select.playlist_content
    - input_select.playlist_source
    - script.playlist_remote

#################################################################
## Inputs

input_select:
  playlist_content:
    name: 'Content:'
    options:
      - Michigan Radio
      - "WRCJ 90.9 FM"
      - Dinner
      - Jazz
      - Chicago Blues
      - Rob's Favorites
      - Ocean Sounds
    icon: mdi:playlist-play

  playlist_source:
    name: 'Source:'
    options:
      - Kitchen Stereo
      - Bedroom Speaker
      - Living Room TV
      - Kitchen/Bedroom
    initial: Kitchen Stereo
    icon: mdi:speaker-wireless

#################################################################
## Scripts
script:

  playlist_remote:
    sequence:

  playlist_action:
    sequence:

      - service: media_player.play_media
        data_template:
          entity_id: media_player.mopidy
          media_content_type: 'audio/mp4'
          media_content_id: >
            {% if is_state("input_select.playlist_content", "Michigan Radio") %} tunein:station:s23407
            {% elif is_state("input_select.playlist_content", "WRCJ 90.9 FM") %} tunein:station:s28356
            {% elif is_state("input_select.playlist_content", "Dinner") %} !secret PLDinner
            {% elif is_state("input_select.playlist_content", "Jazz") %} !secret PLJazz
            {% elif is_state("input_select.playlist_content", "Chicago Blues") %} !secret PLBlues
            {% elif is_state("input_select.playlist_content", "Rob's Favorites") %} !secret PLRobs
            {% elif is_state("input_select.playlist_content", "Ocean Sounds") %} local:track:waves.mp3
            {% endif %}
      - delay: "00:00:02"
      - service: media_player.play_media
        data_template:
          media_content_id: !secret PLAction
          media_content_type: 'audio/mp4'
          entity_id: >
            {% if is_state("input_select.playlist_source", "Kitchen Stereo") %} media_player.kitchen_stereo
            {% elif is_state("input_select.playlist_source", "Bedroom Speaker") %} media_player.bedroom_speaker
            {% elif is_state("input_select.playlist_source", "Living Room TV") %} media_player.living_room_tv
            {% elif is_state("input_select.playlist_source", "Kitchen/Bedroom") %} media_player.kitchenbedroom
            {% endif %}

  playlist_volup:
    sequence:
      service: media_player.volume_up
      data_template:
        entity_id: >
          {% if is_state("input_select.playlist_source", "Kitchen Stereo") %} media_player.nadc338
          {% elif is_state("input_select.playlist_source", "Bedroom Speaker") %} media_player.bedroom_speaker
          {% elif is_state("input_select.playlist_source", "Living Room TV") %} media_player.living_room_tv
          {% elif is_state("input_select.playlist_source", "Kitchen/Bedroom") %} media_player.kitchenbedroom
          {% endif %}

  playlist_voldown:
    sequence:
      service: media_player.volume_down
      data_template:
        entity_id: >
          {% if is_state("input_select.playlist_source", "Kitchen Stereo") %} media_player.nadc338
          {% elif is_state("input_select.playlist_source", "Bedroom Speaker") %} media_player.bedroom_speaker
          {% elif is_state("input_select.playlist_source", "Living Room TV") %} media_player.living_room_tv
          {% elif is_state("input_select.playlist_source", "Kitchen/Bedroom") %} media_player.kitchenbedroom
          {% endif %}

  playlist_stop:
    sequence:
      - service: homeassistant.turn_off
        entity_id: media_player.mopidy
      - service: homeassistant.turn_off
        data_template:
          entity_id: >
            {% if is_state("input_select.playlist_source", "Kitchen Stereo") %} media_player.kitchen_stereo
            {% elif is_state("input_select.playlist_source", "Bedroom Speaker") %} media_player.bedroom_speaker
            {% elif is_state("input_select.playlist_source", "Living Room TV") %} media_player.living_room_tv
            {% elif is_state("input_select.playlist_source", "Kitchen/Bedroom") %} media_player.kitchenbedroom
            {% endif %}

#################################################################
## Automations
automation:

  # Turn off Mopidy when not in use
  - alias: Mopidy turn off

    trigger:
      - platform: state
        entity_id: media_player.kitchen_stereo
        to: 'off'
      - platform: state
        entity_id: media_player.bedroom_speaker
        to: 'off'
      - platform: state
        entity_id: media_player.living_room_tv
        to: 'off'
      - platform: state
        entity_id: media_player.kitchenbedroom
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.kitchen_stereo
          state: 'off'
        - condition: state
          entity_id: media_player.bedroom_speaker
          state: 'off'
        - condition: state
          entity_id: media_player.living_room_tv
          state: 'off'
        - condition: state
          entity_id: media_player.kitchenbedroom
          state: 'off'

    action:
      - service: homeassistant.turn_off
        entity_id: media_player.mopidy
