
#################################################
## Customize

homeassistant:
  customize:

    script.vizio_remote:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        row_height: 40px
        column_width: 52px
        gap: 25px
        entities:
          - entity: script.blackhole
            label: 'TV:'
            column: 1
            row: 1
            color: '#ffffff'
            text_color: '#000000'
          - entity: media_player.viziotv
            icon: mdi:monitor
            color_on: '#E45E65'
            color_off: '#7F848E'
            column: 2
            row: 1
          - entity: script.vizio_tv_voldown
            icon: mdi:volume-medium
            color: '#7F848E'
            column: 3
            row: 1            
          - entity: script.vizio_tv_volup
            icon: mdi:volume-high
            color: '#7F848E'
            column: 4
            row: 1

    script.nad_remote:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 5
        row_height: 40px
        column_width: 52px
        gap: 25px
        entities:
          - entity: script.blackhole
            label: 'Stereo:'
            column: 1
            row: 1
            color: '#ffffff'
            text_color: '#000000'
          - entity: script.nad_poweron
            icon: mdi:speaker
            color: '#7F848E'
            column: 2
            row: 1
          - entity: script.nad_poweroff
            icon: mdi:speaker-off
            color: '#7F848E'
            column: 3
            row: 1
          - entity: script.nad_voldown
            icon: mdi:volume-medium
            color: '#7F848E'
            column: 4
            row: 1            
          - entity: script.nad_volup
            icon: mdi:volume-high
            color: '#7F848E'
            column: 5
            row: 1

    script.light_remote:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        row_height: 40px
        column_width: 52px
        gap: 25px
        entities:
          - entity: script.blackhole
            label: 'Scenes:'
            column: 1
            row: 1
            color: '#ffffff'
            text_color: '#000000'
          - entity: script.scene_nighttime
            icon: mdi:hotel
            color: '#7F848E'
            column: 2
            row: 1
          - entity: script.scene_doglights
            icon: mdi:paw
            color: '#7F848E'
            column: 3
            row: 1
          - entity: script.scene_everything_off
            icon: mdi:flash-off
            color: '#7F848E'
            column: 4
            row: 1

    script.playlist_remote:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        row_height: 40px
        column_width: 52px
        gap: 25px
        entities:
          - entity: script.playlist_action
            icon: mdi:play
            color: '#7F848E'
            column: 1
            row: 1
          - entity: script.playlist_stop
            icon: mdi:stop
            color: '#7F848E'
            column: 2
            row: 1
          - entity: script.playlist_voldown
            icon: mdi:volume-medium
            color: '#7F848E'
            column: 3
            row: 1
          - entity: script.playlist_volup
            icon: mdi:volume-high
            color: '#7F848E'
            column: 4
            row: 1


##################################################
## Groups
group:

  vizio_remote:
    control: hidden
    name: Living Room TV
    entities:
      - script.vizio_remote

  nad_remote:
    control: hidden
    name: Kitchen Stereo
    entities:
      - script.nad_remote


##################################################
## Scripts
script:

  vizio_remote:
    sequence:

  nad_remote:
    sequence:

  light_remote:
    sequence:

  playlist_remote:
    sequence:

  blackhole:
    sequence:
