
#################################################################
## Customize
homeassistant:
  customize:

    alarm_control_panel.main:
      friendly_name: Status
      icon: mdi:shield

    device_tracker.user1:
      friendly_name: !secret user1

    device_tracker.user2:
      friendly_name: !secret user2

    device_tracker.user3:
      friendly_name: !secret user3

    device_tracker.user4:
      friendly_name: !secret user4

    binary_sensor.bathroom_motion_sensor:
      friendly_name: Bathroom
      icon: mdi:run
    binary_sensor.hallway_motion1_sensor:
      friendly_name: Hallway 1
      icon: mdi:run
    binary_sensor.hallway_motion2_sensor:
      friendly_name: Hallway 2
      icon: mdi:run
    binary_sensor.uplivingroom_motion_sensor:
      friendly_name: Up Living
      icon: mdi:run
    binary_sensor.upoffice_motion_sensor:
      friendly_name: Up Office
      icon: mdi:run
    sensor.frontdoor_contact:
      device_class: opening
      icon: mdi:door
    sensor.sidedoor_contact:
      device_class: opening
      icon: mdi:door
    sensor.backdoor_contact:
      device_class: opening
      icon: mdi:door

    lock.front_door_handle_locked:
      friendly_name: Front Door Lock
      icon: mdi:lock-smart

    camera.frontdoor:
      friendly_name: Frontdoor Camera
  
    camera.backdoor:
      friendly_name: Backdoor Camera

#################################################################
## Groups
group:

  locks:
    name: Locks
    entities:
      - lock.front_door_handle_locked

  zmevents:
    name: Camera Events
    entities:
      - sensor.backdoor_events
      - sensor.frontdoor_events

  sensors:
    name: Sensors
    entities:
      - device_tracker.user1
      - device_tracker.user2
      - device_tracker.user3
      - device_tracker.user4
      - sensor.frontdoor_contact
      - sensor.sidedoor_contact
      - sensor.backdoor_contact
      - binary_sensor.uplivingroom_motion_sensor
      - binary_sensor.upoffice_motion_sensor
      - binary_sensor.hallway_motion1_sensor
      - binary_sensor.hallway_motion2_sensor
      - binary_sensor.bathroom_motion_sensor

  alarmcontrol:
    name: Alarm Control
    control: hidden
    entities:
      - alarm_control_panel.main
      - input_boolean.enable_alarm_system
      - input_boolean.enable_armed_home
      - input_boolean.enable_armed_away


#################################################################
## Sensors
sensor: 

#Sensative Strips BS
  - platform: template
    sensors:
      frontdoor_contact:
        friendly_name: Frontdoor
        value_template: >-
          {% if is_state("sensor.frontdoor_contact_access_control", "22") %}
          open
          {% else %}
          closed
          {% endif %}

  - platform: template
    sensors:
      sidedoor_contact:
        friendly_name: Sidedoor
        value_template: >-
          {% if is_state("sensor.sidedoor_contact_access_control", "22") %}
          open
          {% else %}
          closed
          {% endif %}

  - platform: template
    sensors:
      backdoor_contact:
        friendly_name: Backdoor
        value_template: >-
          {% if is_state("sensor.backdoor_contact_access_control", "22") %}
          open
          {% else %}
          closed
          {% endif %}


#################################################################
## Automations
automation:

# Auto set status for Armed Home
  - alias: Auto Status - Armed Home

    trigger:
      - platform: time
        at: '00:00:01'

    condition:
      condition: and
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: device_tracker.user1
              state: 'home'
            - condition: state
              entity_id: device_tracker.user2
              state: 'home'
            - condition: state
              entity_id: device_tracker.user3
              state: 'home'
            - condition: state
              entity_id: device_tracker.user4
              state: 'home'
        - condition: state
          entity_id: alarm_control_panel.main
          state: disarmed
        - condition: state
          entity_id: input_boolean.enable_alarm_system
          state: 'on'
        - condition: state
          entity_id: input_boolean.enable_armed_home
          state: 'on'

    action:
      service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.main

# Trigger for Alarm Home
  - alias: Alarm - Armed Home

    trigger:
      - platform: state
        entity_id: sensor.frontdoor_contact, sensor.sidedoor_contact, sensor.backdoor_contact
        from: 'closed'
        to: 'open'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.enable_alarm_system
          state: 'on'
        - condition: state
          entity_id: input_boolean.enable_armed_home
          state: 'on'
        - condition: state
          entity_id: alarm_control_panel.main
          state: armed_home

    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.main


# Auto rearm for Armed Home (when someone comes home)
  - alias: Auto Status - Rearm Home

    trigger:
      - platform: state
        entity_id: device_tracker.user1, device_tracker.user2, device_tracker.user3, device_tracker.user4
        from: 'not_home'
        to: 'home'

    condition:
      condition: and
      conditions:
        - condition: time
          after: '00:00:01'
          before: '04:55:00'
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.main
              state: pending
            - condition: state
              entity_id: alarm_control_panel.main
              state: armed_home
        - condition: state
          entity_id: input_boolean.enable_alarm_system
          state: 'on'
        - condition: state
          entity_id: input_boolean.enable_armed_home
          state: 'on'

    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.main
      - delay: '00:10:00'
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.main

# Auto Disarm for Armed Home
  - alias: Auto Status - Disarm Home

    trigger:
      - platform: time
        at: '05:00:00'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: alarm_control_panel.main
          state: armed_home
        - condition: state
          entity_id: input_boolean.enable_alarm_system
          state: 'on'
        - condition: state
          entity_id: input_boolean.enable_armed_home
          state: 'on'

    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.main


# Auto set status for Armed Away
  - alias: Auto Status - Armed Away

    trigger:
      - platform: state
        entity_id: device_tracker.user1, device_tracker.user2, device_tracker.user3, device_tracker.user4
        from: 'home'
        to: 'not_home'

    condition:
      condition: and
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.main
              state: disarmed
            - condition: state
              entity_id: alarm_control_panel.main
              state: armed_home
        - condition: state
          entity_id: device_tracker.user1
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.user2
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.user3
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.user4
          state: 'not_home'
        - condition: state
          entity_id: input_boolean.enable_alarm_system
          state: 'on'
        - condition: state
          entity_id: input_boolean.enable_armed_away
          state: 'on'

    action:
      service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.main

# Trigger for Alarm Away
  - alias: Alarm - Armed Away

    trigger:
      - platform: state
        entity_id: sensor.frontdoor_contact, sensor.sidedoor_contact, sensor.backdoor_contact
        from: 'closed'
        to: 'open'
      - platform: state
        entity_id: binary_sensor.hallway_motion1_sensor, binary_sensor.hallway_motion2_sensor, binary_sensor.uplivingroom_motion_sensor, binary_sensor.upoffice_motion_sensor
        from: 'off'
        to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.enable_alarm_system
          state: 'on'
        - condition: state
          entity_id: input_boolean.enable_armed_away
          state: 'on'
        - condition: state
          entity_id: alarm_control_panel.main
          state: armed_away

    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.main


# Auto disarm for Armed Away
  - alias: Auto Status - Disarmed Away

    trigger:
      - platform: state
        entity_id: device_tracker.user1, device_tracker.user2, device_tracker.user3, device_tracker.user4
        from: 'not_home'
        to: 'home'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.enable_alarm_system
          state: 'on'
        - condition: state
          entity_id: input_boolean.enable_armed_away
          state: 'on'
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.main
              state: pending
            - condition: state
              entity_id: alarm_control_panel.main
              state: armed_away

    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.main


# Disable alarm
  - alias: Disable Alarm System

    trigger:
      - platform: state
        entity_id: input_boolean.enable_alarm_system
        from: 'on'
        to: 'off'

    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.main


# Disarm when notifcation clicked
  - alias: Notifcation Disarm

    trigger:
      - platform: event
        event_type: html5_notification.clicked
        event_data:
          action: disarm_ha

    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.main


# Notification when alarm pending
#  - alias: Notify when alarm is pending
#
#    trigger:
#      - platform: state
#        entity_id: alarm_control_panel.main
#        from: 'armed_away'
#        to: 'pending'
#      - platform: state
#        entity_id: alarm_control_panel.main
#        from: 'armed_home'
#        to: 'pending'

#    action:
#      - service: notify.html5
#        data:
#          title: 'Alarm Pending'
#          message: "Your home alarm is pending for an alarm."
#          data:
#            image: !secret frontdoorimage
#            requireInteraction: true
#            renotify: true
#            tag: 'ha_alarm'
#            url: '/states/group.security'
#            actions:
#              - action: 'disarm_ha'
#                title: 'Disarm'

# Notification when alarm triggerd
  - alias: Notify when alarm is triggered

    trigger:
      - platform: state
        entity_id: alarm_control_panel.main
        from: 'pending'
        to: 'triggered'

    action:
      - service: notify.html5
        data:
          title: 'ALARM!'
          message: "ALARM! Your home alarm has been triggered."
          data:
            image: !secret frontdoorimage
            requireInteraction: true
            renotify: true
            tag: 'ha_alarm'
            url: '/states/group.security'
            actions:
              - action: 'disarm_ha'
                title: 'Disarm'
      - service: notify.twilio_calling
        data:
          message: 'Your home assistant security alarm has been triggered.'
          target:
            - !secret notificationtarget

# Notification when alarm disarmed
  - alias: Notify when alarm is disarmed

    trigger:
      - platform: state
        entity_id: alarm_control_panel.main
        from: 'triggered'
        to: 'disarmed'

    condition:
      - condition: state
        entity_id: input_boolean.enable_alarm_system
        state: 'on'

    action:
      - service: notify.html5
        data:
          title: 'Disarmed'
          message: "Your home alarm has been disarmed."
          data:
            requireInteraction: false
            renotify: false
            silent: true
            noscreen: true
            tag: 'ha_alarm'
            url: '/states/group.security'


##################################################
## Inputs
input_boolean:

  enable_alarm_system:
    name: Alarm System Enabled
    initial: on
    icon: mdi:toggle-switch

  enable_armed_home:
    name: Home Armed Active
    initial: on
    icon: mdi:bell-ring

  enable_armed_away:
    name: Away Armed Active
    initial: on
    icon: mdi:bell-ring
