
#################################################################
## Groups
group:

  things:
    name: Things
    control: hidden
    entities:
      - switch.vizio_tv
      - switch.nad_stereo
      - switch.bedroom_outlet_switch_3
      - switch.kitchen_outlet_switch
      - sensor.dishwasher_status
      - vacuum.roomba
      - climate.dining_room


#################################################################
## Customize
homeassistant:
  customize:

    sensor.dishwasher_status:
      friendly_name: Dishwasher
      icon: mdi:washing-machine

    switch.meter_outlet_switch:
      friendly_name: Dishwasher Switch

    switch.bedroom_outlet_switch_3:
      friendly_name: Bedroom Fan
      icon: mdi:fan

    switch.kitchen_outlet_switch:
      friendly_name: Espresso Machine
      icon: mdi:coffee

    switch.bedroom_outlet_switch_2:
      friendly_name: Bedroom Outlet Left

    climate.dining_room:
      friendly_name: Thermostat


#################################################################
## Scripts

script:

  roomba_on:
    sequence:
      - service: homeassistant.turn_on
        entity_id: vacuum.roomba


#################################################################
## Sensors
sensor:

  - platform: template
    sensors:
      dishwasher_status:
        value_template: '{{ states.input_select.dishwasher_status.state}}'
        friendly_name: 'Dishwasher Status'

  - platform: template
    sensors:
      roomba_status:
        value_template: '{{ states.vacuum.roomba.attributes.status}}'
        friendly_name: 'Roomba Status'


##################################################
## Inputs
input_select:

  dishwasher_status:
    name: Dishwasher Status
    options:
      - Running
      - Drying
      - 'Off'
    initial: 'Off'


#################################################################
## Automations
automation:

  # Espresso Notify
  - alias: Espresso Notify

    trigger:
      platform: state
      entity_id: switch.kitchen_outlet_switch
      to: 'on'
      for:
        minutes: 30

    action:
      - service: notify.html5
        data:
          title: 'Espresso Ready'
          message: 'Espresso machine is warmed up.'
          data:
            requireInteraction: true


#Roomba logic
  # Sceduled Roobma!!
  - alias: Roomba On Weekdays

    trigger:
      - platform: time
        at: '10:00:00'

    condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: template
          value_template: '{{states.vacuum.roomba.attributes.battery_level > 79}}'
        - condition: state
          entity_id: input_boolean.vacation_mode
          state: 'off'

    action:
      - service: homeassistant.turn_on
        entity_id: vacuum.roomba

  # Notify when Roomba is stuck or stopped
  - alias: Roomba notify stuck or stopped

    trigger:
      - platform: state
        entity_id: vacuum.roomba
        to: 'off'
        for:
          minutes: 1

    condition:
      condition: or
      conditions:
        - condition: template
          value_template: '{{states.vacuum.roomba.attributes.status == "Stuck"}}'
        - condition: template
          value_template: '{{states.vacuum.roomba.attributes.status == "Stopped"}}'

    action:
      - service: notify.html5
        data:
          title: 'Roomba Error'
          message: 'Schmidt is stuck or something else stopped him.'
          data:
            requireInteraction: true
            renotify: true
            tag: 'roomba_notify'

  # Notify when Roomba cant find dock
  - alias: Roomba notify cant find dock

    trigger:
      - platform: state
        entity_id: sensor.roomba_status
        from: 'User Docking'
        to: 'Stopped'

#    condition:
#      - condition: template
#        value_template: '{{states.vacuum.roomba.attributes.battery_level > 21}}'

    action:
      - service: notify.html5
        data:
          title: 'Roomba Error'
          message: 'Schmidt is lost and cant find his dock.'
          data:
            requireInteraction: true
            renotify: true
            tag: 'roomba_notify'

  # Notify when Roomba is finished
  - alias: Roomba notify finished

    trigger:
      - platform: state
        entity_id: sensor.roomba_status
        from: 'User Docking'
        to: 'Charging'
      - platform: state
        entity_id: sensor.roomba_status
        from: 'Docking - End Mission'
        to: 'Charging'

    action:
      - service: notify.html5
        data:
          title: 'Roomba Finished'
          message: 'Schmidt is finished and bin needs emptying.'
          data:
            requireInteraction: true
            renotify: true
            tag: 'roomba_notify'

  # Notify when Roomba battery very low
  - alias: Roomba notify battery very low

    trigger:
      - platform: template
        value_template: '{{states.vacuum.roomba.attributes.battery_level < 11}}'

    action:
      - service: notify.html5
        data:
          title: 'Roomba Error'
          message: 'Schmidt battery is 10%.'
          data:
            requireInteraction: true
            renotify: true
            tag: 'roomba_notify'


#Dishwasher logic
  # Dishwasher set running
  - alias: Set dishwasher active when power detected

    trigger:
      - platform: numeric_state
        entity_id: sensor.meter_outlet_power
        above: 10

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: 'Off'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Running

  # Dishwasher set drying
  - alias: Set dishwasher drying when power drops

    trigger:
      - platform: numeric_state
        entity_id: sensor.meter_outlet_power
        below: 600
        above: 380
        for:
          minutes: 2

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Running

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Drying

  # Dishwasher set off
  - alias: Set dishwasher off

    trigger:
      - platform: numeric_state
        entity_id: sensor.meter_outlet_power
        below: 5
        for:
          minutes: 6

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: 'Off'

  # Dishwasher Alert when done
  - alias: Send alert when dishwasher is done

    trigger:
      - platform: state
        entity_id: input_select.dishwasher_status
        to: 'Off'

    action:
      - service: notify.html5
        data:
          title: 'Dishwasher Finished'
          message: 'The Dishwasher has finished and is ready to be emptied.'
          data:
            requireInteraction: true
